### ISSUE TITLE
Binary generated doesn't run on MCH2022 badge

### ISSUE THREAD

**Issue by jhaand** [jhaand/rust4mch#3]
Actions:
Run latest firmware from the MCH2022 firmware repository (2022-06-15)
Build an ELF binary with `cargo run`
Generate stripped binary file via `esptool --chip esp32 elf2image rust4ch`
Copy it to uSD card and install it as an app. 
Run the app. 

Expected. 
View the message ""Hello MCH2022 from Rust!" and info on serial console. 

Observed:
The bootloader starts and then freezes a moment after encountering the application. 
Then the bootloader restart and goes to the main menu. 

Extra: 
See logfile [rust4mch_log.txt](https://github.com/jhaand/rust4mch/files/8908848/rust4mch_log.txt)

**Comment by jhaand** [comment]
Added the hello world example and tried to run using a hello world example using the Arduino IDE.
The hello world example from this repository still fails. Compile and run with:
```
cargo build --example hello_world
cd target/xtensa-esp32-espidf/debug/examples/
esptool.py --chip esp32 elf2image hello_world
../../../../tools/webusb_push.py hello_world hello_world.bin
```
The app starts and then causes a restart with the following error message. 

`(139) bootloader: No AppFS app selected or failed to open app, starting launcher (-1)!`

This Arduino sketch runs fine. Compile it with the Arduino IDE and export the .bin. Then uploadi the .bin with the 'webusb_push.py' script. 
```
#include <esp_system.h>
#include "soc/rtc.h"
#include "soc/rtc_cntl_reg.h"

void return_to_launcher() {
  REG_WRITE(RTC_CNTL_STORE0_REG, 0);
  esp_restart();
}

void setup() {
  Serial.begin(115200);
  Serial.println("Hello MCH2022!");

}

void loop() {
  static int i=0;
  
  delay(700);
  Serial.print("period no.: ");
  Serial.println(i++);
  if (i > 10)
  {
    return_to_launcher();
  }
}
```

**Comment by jhaand** [comment]
Any idea @SergioGasquez on what might help with this issue?

**Comment by SergioGasquez** [comment]
Hello @jhaand! 
Do you mind elaborating on why the `flash.sh` approach is unavailable and why you use an uSD? (Sorry, I don't have much background on the badge).

By the way, [`cargo-espflash` can also save application binaries](https://github.com/esp-rs/espflash/tree/master/cargo-espflash#usage) with `cargo espflash save-image` subcommand.

**Comment by jhaand** [comment]
At the moment I don't need to use the uSD any more. I now use the script with web-usb. 

We need to use the custom script with web-usb, because hardware wise the RP2040 lies between the USB and the ESP32. As you can see in the schematic of the badge. [badge-hardware](https://github.com/badgeteam/mch2022-badge-hardware)  And the binaries need to be saved as separate apps. Just uploading it to a certain address can interfere with the normal launcher. 
I can try to flash via the web-flash later. 
When I try the `cargo espflash save-image` I get the same size as before (but a different hash) 
Unfortunately this also doesn't work and it looks like the watchdog kicks in after 9 seconds. [link to docs](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/startup.html)

**Comment by SergioGasquez** [comment]
Maybe try `cargo espflash save-image --merge` which stores partition table, bootloader, and application binaries into a single binary.

**Comment by jhaand** [comment]
Using the `--merge` option didn't work. The image becomes even too large to download. 

Further discussion indicates that I actually have too much stuff in the object file. I need to strip the bootloader and partition info from the ELF file before creating the .bin file. Or make sure to create an object file without these things.

**Comment by SergioGasquez** [comment]
Sad to hear that 😢 maybe someone in our matrix channel has more experience than me in this regard and can help:  [#esp-rs:matrix.org](https://matrix.to/#/#esp-rs:matrix.org). In any case, I will also ask my teammates for help!

**Comment by jhaand** [comment]
OK. Thanks for the input and I will check it out.

**Comment by Spritetm** [comment]
FYI, the MCH uses appfs, which is a filesystem designed to load (ESP-IDF) app files directly from the internal flash. It means the boot process is a bit different from a normal (ESP-IDF) app, as in: the bootloader is aware of the filesystem and uses the MMU to 'assemble' a possibly-discontinuous on-flash file into a memory layout that is continuous and would (normally) allow the app to boot as if it were loaded from a partition like a normal ESP-IDF app. That's likely leading to issues here: I'll admit to knowing very little about Rust on the ESP32, but if it makes assumptions about what its app looks like on-flash or messes with the MMU assuming the app is contiguous on-flash, it'll break.

**Comment by jhaand** [comment]
I think I will park this issue for now. I tried to do the Arduino 'hello world' using Platformio. Which results in a boot loop. So the support for creating binaries that work via the launcher is limited to the Arduino IDE and I can't find any relevant documentation to solve this.

That leaves me more time to develop working features using the espflash method.

Especially since building and flashing the launcher just goes that easy. That makes it really easy to try firmware images.

**Comment by jhaand** [comment]
@renzenicolai  from Badgeteam mentioned that the MCH badge will lock out esptool flashing. Only loading apps will be allowed. So this issue needs to be fixed. 

Copied from discussion yesterday:
```Renze Nicolai, [29 Jun 2022 21:19:58]
One of the features that's going to be in there is disabling the esptool.py reset method

Renze Nicolai, [29 Jun 2022 21:20:06]
so that people don't accidently wipe the launcher

Renze Nicolai, [29 Jun 2022 21:20:12]
so please do try to get it working as app

Renze Nicolai, [29 Jun 2022 21:20:19]
else you will find yourself to be disappointed

Renze Nicolai, [29 Jun 2022 21:20:52]
and yes the bootloader works, we can boot arduino & esp-idf apps, also platformio idf apps work too, platformio-arduino fails for some reason```

Try to get a standard template going from Espressif and Cargo generate:
```cargo install cargo-generate
cargo generate --git https://github.com/esp-rs/esp-idf-template cargo ```

**Comment by renzenicolai** [comment]
Note that a user can disable the protection against accidentally flashing simply by pressing the A button when the warning is shown or in the menu by going to the settings and disabling the flashing lock there.

Installing apps using the provided tooling is still the preferred way and I hope we can figure out what is going wrong here.

**Comment by jhaand** [comment]
Thanks for the heads up. I will try the platformio IDF default and the Rust ESP IDF template on the badge shortly. But this surely has to do with some build scripts somewhere.

**Comment by jhaand** [comment]
Solved this issue by copying the config files from the esp-rd/badge.team templates, `cargo clean` and a `rm -rf ./embuild`
